default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password

development:
  <<: *default
  database: weather_development

test:
  <<: *default
  database: weather_test

production:
  <<: *default
  database: weather_production

